# Math 5389 Project 3 

## Servet Oksuz

### 1.1 What is the transpose of a matrix? 

Transpose of a matrix is a new matrix whose columns are the rows of the original matrix

### 1.2 Create a new dataset called “cars2” which selects the first four rows from the dataset “mtcars” and the first 3 columns of the dataset “mtcars”.   Find the transpose of the matrix “cars2”.  
 

In [15]:
cars2 <- mtcars[1:4, 1:3]
cars2

mpg  cyl disp
Mazda RX4      21.0 6   160 
Mazda RX4 Wag  21.0 6   160 
Datsun 710     22.8 4   108 
Hornet 4 Drive 21.4 6   258

In [16]:
t(cars2)

Mazda RX4 Mazda RX4 Wag Datsun 710 Hornet 4 Drive
mpg   21        21            22.8       21.4         
cyl    6         6             4.0        6.0         
disp 160       160           108.0      258.0

## Question 2  Consider the following properties of the transpose of a matrix:   

### 2.1 Consider the matrix C defined as: C <- matrix(c(1,2,3,4,5,6,7,8,9),nrow=3) Is C symmetric?  

In [1]:
C <- matrix(c(1,2,3,4,5,6,7,8,9),nrow=3)

In [2]:
C

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [18]:
C == t(C)

[,1]  [,2]  [,3] 
[1,]  TRUE FALSE FALSE
[2,] FALSE  TRUE FALSE
[3,] FALSE FALSE  TRUE

C is not symmetric

### 2.2 Consider the matrix D defined as: D <- matrix(c(1,2,3,4,5,6,7,8,9),nrow=3,byrow=T) Is D symmetric?

In [3]:
D <- matrix(c(1,2,3,4,5,6,7,8,9),nrow=3,byrow=T)
D

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [19]:
D == t(D)

[,1]  [,2]  [,3] 
[1,]  TRUE FALSE FALSE
[2,] FALSE  TRUE FALSE
[3,] FALSE FALSE  TRUE

D is not symmetric

### 2.3 Use the R software to show that  (CD)T=DTCT 

In [7]:
t(C*D)

[,1] [,2] [,3]
[1,]  1    8   21  
[2,]  8   25   48  
[3,] 21   48   81

In [6]:
t(D)*t(C)

[,1] [,2] [,3]
[1,]  1    8   21  
[2,]  8   25   48  
[3,] 21   48   81

In [11]:
t(C*D) == t(D)*t(C)

[,1] [,2] [,3]
[1,] TRUE TRUE TRUE
[2,] TRUE TRUE TRUE
[3,] TRUE TRUE TRUE

It is symmetric

### 2.4 Use the R software to show that  (C+D)T=CT+DT 

In [8]:
t(C+D)

[,1] [,2] [,3]
[1,]  2    6   10  
[2,]  6   10   14  
[3,] 10   14   18

In [9]:
t(C)+t(D)

[,1] [,2] [,3]
[1,]  2    6   10  
[2,]  6   10   14  
[3,] 10   14   18

In [10]:
t(C+D) == t(C)+t(D)

[,1] [,2] [,3]
[1,] TRUE TRUE TRUE
[2,] TRUE TRUE TRUE
[3,] TRUE TRUE TRUE

It is symmetric

## Question 3

In [12]:
M <- matrix(c(2, 3, 1, 2,
 4, 2, 3, 4,
 1, 4, 2, 2,
 3, 1, 0, 1), nrow=4, ncol=4, byrow=TRUE)

In [13]:
det(M)

[1] 15

## Question 4 Inner product of vectors:  

In [21]:
a <- c(1, 3, 2) 
b <- c(2, 8, 9) 
sum(a*b)

[1] 44

## Question 5 The length or norm of a vector:   

In [42]:
paste0("The length of vector a is: ", sqrt(sum(a*a)))

[1] "The length of vector a is: 3.74165738677394"

In [43]:
paste0("The length of vector b is: ", sqrt(sum(b*b)))

[1] "The length of vector b is: 12.2065556157337"

## Question 6 Orthogonal or perpendicular vectors:  

In [44]:
v1 <- c(1,1) 
v2 <- c(-1,1)

In [47]:
if (sum(v1*v2) == 0){
    print("Two vectors are orthogonal")
} else {
    print(" Two vectors are not orthogonal")
}

[1] "Two vectors are orthogonal"


## Question 7 Inverse of a diagonal matrix: 

In [49]:
# Let's define A
A <- matrix(c(2,0,0,0,3,0,0,0,4),nrow=3)
A

[,1] [,2] [,3]
[1,] 2    0    0   
[2,] 0    3    0   
[3,] 0    0    4

In [51]:
# Let's find the inverse of A
solve(A)

[,1] [,2]      [,3]
[1,] 0.5  0.0000000 0.00
[2,] 0.0  0.3333333 0.00
[3,] 0.0  0.0000000 0.25

## Question 8: Least squares:

### 8.1 I did on a piece of paper

### 8.2 Define X and y as follows:

In [55]:
x <- matrix(c(1,1,1,1,1,1,2,3,4,5), nrow=5)
x

[,1] [,2]
[1,] 1    1   
[2,] 1    2   
[3,] 1    3   
[4,] 1    4   
[5,] 1    5

In [53]:
y <- c(3.7,4.2,4.9, 5.7, 6.9)
y

[1] 3.7 4.2 4.9 5.7 6.9

### Find B^

In [63]:
solve(t(x)%*%x)%*%t(x)%*%y

[,1]
[1,] 2.71
[2,] 0.79